# Site settings
title: SuYi Blog
description: Modern-Blog A Elegant template for Jekyll
keywords: SuYi, Blog, Harris
author: SuYi
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.haojiacheng.cn" # the base hostname & protocol for your site
