title: 苏弋的博客
description: > # this means to ignore newlines until "baseurl:"
  Blog with theme Future Imperfect<br>
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.haojiacheng.cn" # the base hostname & protocol for your site, e.g. http://example.com


author:
  name: 'SuYiHarris'
  last_name: 'Harris'
  cv: '//www.haojiacheng.cn'
  avatar: '/images/app.png'
  github_username:  SuYiHarris  
  email: 990784805@qq.com
  logo: '/images/logo.svg'

# Build settings
markdown: markdown

permalink: /:categories/:year/:title.md


